name: add-labels
on: 
  workflow_dispatch:

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1      
      - name: Synchronize labels
        uses: julb/action-manage-label@v1
        with:
          from: .github/config/labels.yml
          skip_delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}