name: Mark issues "default"

on:
  schedule:
  - cron: "0 0/3 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is marked default for generating issues report.'
        stale-issue-label: 'default'
        days-before-stale: 0
        days-before-close: -1
        operations-per-run: 100
