name: Mark stale issues

on:
  schedule:
    - cron: "0 0/3 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open for 7 days with no activity."
          stale-issue-label: "stale"
          days-before-stale: 7
          days-before-close: -1
          operations-per-run: 100
          exempt-issue-labels: "backlog"
